### ISSUE TITLE
OK, u's guys. What's going on?

### ISSUE THREAD

**Issue by mgmartin-51** [jackiekazil/data-wrangling#2]
While running the code in Chapter 3, importing the .json data file, the script worked fine, but the output was thus:

{u'Indicator': u'Healthy life expectancy (HALE) at birth (years)', u'Country': u'Zambia', u'Comments': u'', u'Display Value': 36, u'World Bank income group': u'Low-income', u'Numeric': 36.0, u'Sex': u'Both sexes', u'High': u'', u'Low': u'', u'Year': 2000, u'WHO region': u'Africa', u'PUBLISH STATES': u'Published'}
{u'Indicator': u'Healthy life expectancy (HALE) at birth (years)', u'Country': u'Zimbabwe', u'Comments': u'', u'Display Value': 51, u'World Bank income group': u'Low-income', u'Numeric': 51.0, u'Sex': u'Female', u'High': u'', u'Low': u'', u'Year': 2012, u'WHO region': u'Africa', u'PUBLISH STATES': u'Published'}

Any idea why all the "u's"?

**Comment by kjam** [comment]
Hi @mgmartin-51,

Thanks for writing! The u'' represents a [Unicode string](https://en.wikipedia.org/wiki/Unicode). In Python 2, strings that are unicode are represented with the u'' in front of them when printed. If you are are curious about how Python handles Unicode versus non-Unicode strings, I recommend [watching Ned Batchelder's PyCon talk on the subject](http://nedbatchelder.com/text/unipain.html). Otherwise, no need to worry. They are strings and operate as such. Let me know if you have any other questions, or if I can close the issue (if it all made sense). Thanks!

-katharine

**Comment by mgmartin-51** [comment]
Thank you! That's fine. I just thought I did something wrong, as the "u's" weren't mentioned in the book, which I am enjoying immensely, by the way!

**Comment by kjam** [comment]
Good to hear! Let us know if anything else comes up and happy pythoning! :)
