### ISSUE TITLE
noob question regarding JSON

### ISSUE THREAD

**Issue by aintbrokedontfix** [jackiekazil/data-wrangling#7]
I noticed on Chap 3 that the JSON structure on the sample data starts with [ (open-bracket) on the first row and ends with a ] (close-bracket); however, the original WHO JSON data only starts with { and ends with }. Can Python handle JSON data that does not start with a bracket?  If I run the book example using the original WHO data, I don't get a full listing of the contents of the data, but just the 5 top-level objects.

Thanks.

**Comment by kjam** [comment]
Hi there,

Sorry for the delayed reply! There are two ways I normally choose to fix this:

1. Edit the file directly if it's as simple as adding open and close brackets.
2. Add those open and close brackets as I read the data in (i.e. data = '[' + read_in_json + ']' )
3. Use https://docs.python.org/3/library/ast.html#ast.literal_eval to read in each dictionary (you must iterate and call split for this).

Technically, the WHO JSON data is invalid, which is why we have to resort to these workarounds. :)

Let me know if that answers your question!
-kj
